# Generated by Django 3.2.9 on 2021-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
