# Generated by Django 3.2.9 on 2021-11-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keaclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'AttendanceCode',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceCode', models.IntegerField()),
                ('date', models.DateField()),
                ('keaclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keaclass.class')),
            ],
            options={
                'db_table': 'AttendanceLog',
            },
        ),
    ]
