# Generated by Django 3.2.9 on 2021-12-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('keaclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceCode', models.IntegerField()),
                ('username_fk', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=8, default=55.70636, max_digits=10)),
                ('long', models.DecimalField(decimal_places=8, default=12.53917, max_digits=10)),
                ('keaclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keaclass.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'db_table': 'AttendanceLog',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(default='22:12:57', max_length=15)),
                ('isActive', models.CharField(default='True', max_length=6)),
                ('keaclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keaclass.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'db_table': 'AttendanceCode',
            },
        ),
    ]
