# Generated by Django 3.2.9 on 2021-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
