# Generated by Django 3.2.9 on 2021-11-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0003_auto_20211122_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
