# Generated by Django 3.2.9 on 2021-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0004_alter_attendancecode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='username_fk',
            field=models.CharField(max_length=12),
        ),
    ]
