# Generated by Django 3.2.9 on 2021-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0005_alter_attendancelog_username_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
