# Generated by Django 3.2.9 on 2021-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0008_auto_20211130_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecode',
            name='isActive',
            field=models.CharField(default='True', max_length=6),
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='time',
            field=models.CharField(default='13:34:45', max_length=15),
        ),
    ]
