# Generated by Django 3.2.9 on 2021-11-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
