# Generated by Django 3.2.9 on 2021-11-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keaclass', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keaclass.class')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
